#!/bin/bash

if [ "$*" = "" ]; then
cat <<EOF
$0: given some guesses and their results, gives the list of remaining possible words

Usage:

  $0 guess result guess result ...

  result is a string with "ygb" characters in it, for "yellow", "green", and "black"

  For example, for results consistent with the 2022-01-17 wordle, try

  $0 aired byyyb resin yyyyb
EOF
exit 1
else
    deno run --allow-read guess.ts $*
fi
